# Generated by Django 3.0.8 on 2020-07-21 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(blank=True, choices=[(1, 'Individual'), (2, 'Company')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('brand_name', models.CharField(max_length=200, null=True)),
                ('address', models.TextField(null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('pin_code', models.CharField(max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('started_in_year', models.DateField(blank=True, null=True)),
                ('website_address', models.URLField(blank=True, null=True)),
                ('profession_type', models.IntegerField(blank=True, choices=[('CA', 'CA'), ('CS', 'CS'), ('Tax_Adviser', 'Tax Adviser'), ('Legal_Adviser', 'Legal Adviser'), ('Analyst', 'Analyst'), ('Business_Adviser', 'Business Adviser'), ('Finance_Adviser', 'Finance Adviser'), ('Diversified', 'Diversified')], null=True)),
                ('speciality_type', models.IntegerField(blank=True, choices=[(1, 'FMCG'), (2, 'Manufacturer'), (3, 'Trader'), (4, 'IMPEX'), (5, 'Retailer'), (6, 'IT'), (7, 'Diversified')], null=True)),
                ('business_cater', models.IntegerField(blank=True, choices=[(1, 'Startup'), (2, 'Small'), (3, 'Medium'), (4, 'Large'), (5, 'Corporate'), (6, 'Institution')], null=True)),
                ('experience', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5+')], null=True)),
                ('annual_business_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('number_of_employees', models.IntegerField(blank=True, null=True)),
                ('core_team_members', models.IntegerField(blank=True, null=True)),
                ('GST_number', models.CharField(blank=True, max_length=15, null=True)),
                ('PAN_number', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='individual_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('contact_person_name', models.CharField(max_length=200, null=True)),
                ('contact_person_mobile', models.CharField(max_length=200, null=True)),
                ('brand_name', models.CharField(max_length=200, null=True)),
                ('address', models.TextField(null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('pin_code', models.CharField(max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('started_in_year', models.DateField(blank=True, null=True)),
                ('website_address', models.URLField(blank=True, null=True)),
                ('company_type', models.IntegerField(blank=True, choices=[(1, 'Partnership'), (2, 'LLP'), (3, 'Pvt Ltd'), (4, 'Ltd'), (5, 'others')], null=True)),
                ('business_type', models.IntegerField(blank=True, choices=[(1, 'FMCG'), (2, 'Manufacturer'), (3, 'Trader'), (4, 'IMPEX'), (5, 'Retailer'), (6, 'IT'), (7, 'Diversified')], null=True)),
                ('business_size', models.IntegerField(blank=True, choices=[(1, 'Startup'), (2, 'Small'), (3, 'Medium'), (4, 'Large'), (5, 'Corporate'), (6, 'Institution')], null=True)),
                ('annual_business_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('number_of_employees', models.IntegerField(blank=True, null=True)),
                ('core_team_members', models.IntegerField(blank=True, null=True)),
                ('GST_number', models.CharField(blank=True, max_length=15, null=True)),
                ('PAN_number', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200, null=True)),
                ('branch_name', models.CharField(max_length=20, null=True)),
                ('ifsc_code', models.CharField(max_length=20, null=True)),
                ('account_number', models.IntegerField(null=True)),
                ('account_type', models.IntegerField(blank=True, choices=[(1, '--------------'), (2, 'Saving Account'), (3, 'Current Account'), (4, 'Overdraft Account')], null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
