# Generated by Django 2.1.15 on 2020-07-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='CompanyUser',
        ),
        migrations.RenameModel(
            old_name='Individual',
            new_name='IndividualUser',
        ),
    ]
