# Generated by Django 3.0.8 on 2020-07-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualuser',
            name='profession_type',
            field=models.IntegerField(blank=True, choices=[(1, 'CA'), (2, 'CS'), (3, 'Tax Adviser'), (4, 'Legal Adviser'), (5, 'Analyst'), (6, 'Business Adviser'), (7, 'Finance Adviser'), (8, 'Diversified')], null=True),
        ),
    ]
