# Generated by Django 3.0.8 on 2020-07-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200721_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualuser',
            name='profession_type',
            field=models.CharField(blank=True, choices=[('CA', 'CA'), ('CS', 'CS'), ('Tax_Adviser', 'Tax Adviser'), ('Legal_Adviser', 'Legal Adviser'), ('Analyst', 'Analyst'), ('Business_Adviser', 'Business Adviser'), ('Finance_Adviser', 'Finance Adviser'), ('Diversified', 'Diversified')], max_length=20, null=True),
        ),
    ]
