# Generated by Django 3.0.8 on 2020-07-15 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_auto_20200708_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(blank=True, choices=[(1, 'Individual'), (2, 'Company')], null=True)),
            ],
        ),
        migrations.AddField(
            model_name='individualuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='speciality_type',
            field=models.IntegerField(blank=True, choices=[(1, 'FMCG'), (2, 'Manufacturer'), (3, 'Trader'), (4, 'IMPEX'), (5, 'Retailer'), (6, 'IT'), (7, 'Diversified')], default=1, null=True),
        ),
    ]
