# Generated by Django 3.0.8 on 2020-07-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200721_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualuser',
            name='business_cater',
            field=models.CharField(blank=True, choices=[('Startup', 'Startup'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Corporate', 'Corporate'), ('Institution', 'Institution')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='speciality_type',
            field=models.CharField(blank=True, choices=[('FMCG', 'FMCG'), ('Manufacturer', 'Manufacturer'), ('Trader', 'Trader'), ('IMPEX', 'IMPEX'), ('Retailer', 'Retailer'), ('IT', 'IT'), ('Diversified', 'Diversified')], max_length=20, null=True),
        ),
    ]
