# Generated by Django 3.0.8 on 2020-07-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200715_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualuser',
            name='speciality_type',
            field=models.IntegerField(blank=True, choices=[(1, 'FMCG'), (2, 'Manufacturer'), (3, 'Trader'), (4, 'IMPEX'), (5, 'Retailer'), (6, 'IT'), (7, 'Diversified')], null=True),
        ),
    ]
