# Generated by Django 3.0.8 on 2020-07-22 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0005_auto_20200721_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bank_detail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('narration', models.CharField(max_length=100, null=True)),
                ('ref_no', models.CharField(max_length=40, null=True)),
                ('value_dt', models.DateField(null=True)),
                ('withdrawal_amt', models.FloatField(blank=True, null=True)),
                ('deposite_amt', models.FloatField(blank=True, null=True)),
                ('closing_balance', models.FloatField(blank=True, null=True)),
                ('bankdetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bank_statement', to='authentication.BankDetails')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bank_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
