# Generated by Django 3.0.8 on 2020-07-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20200722_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='account_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
